Makefile: Run collectstatic in "make run" for non-debug mode
When running "make run" in non-debug mode, collectstatic needs to be
run, otherwise we will see errors like this one:

  ValueError: Missing staticfiles manifest entry for "vue.global.prod.js"